SimformSolutionsPvtLtd/flutter_credit_card

- CHANGELOG.md
- example/lib/main.dart
- lib/credit_card_form.dart
- pubspec.yaml
Feature : Applied Default ThemeData
> Feature : Applied Default ThemeData

- lib/flutter_credit_card.dart
- pubspec.yaml
> Export CreditCardModel to make `as` imports work

- README.md
:sparkles: Updated version in readme file.
> Updated version in readme file.

- lib/credit_card_form.dart
> [feature] Add unfocus in card holder field

- lib/credit_card_form.dart
Reverts SimformSolutionsPvtLtd/flutter_credit_card#42
> Revert "[feature] Add unfocus in card holder field"

- README.md
- example/lib/main.dart
- lib/credit_card_form.dart
- lib/credit_card_widget.dart
> Optional Form Fields and added autofillhints

- lib/credit_card_widget.dart
Fetch upstream and just change the regex
#51 
For web to work need to use Glassmorphism instead of the gradient background.
> Fix Safari on iOS and Web

- lib/credit_card_form.dart
Adding initials values for input so we can initialise each input with a value.
> adding init values

- lib/credit_card_form.dart
Makes entering the date much easier.
> Automatically add leading 0 to expiry date when it starts with 2-9.

- lib/credit_card_form.dart
- added support for custom validator
> fixes #86 Enhancement regarding support of custom validator

- example/lib/main.dart
- fixed known issue regarding background color of validate button.
> fixed: known issue regarding background color of validate button 

- .github/workflows/flutter.yml
- example/lib/app_colors.dart
- lib/credit_card_brand.dart
- add support for flutter workflow
> setup flutter workflows

- .fvm/flutter_sdk
- .fvm/fvm_config.json
- lib/credit_card_form.dart
- lib/credit_card_widget.dart
- added support for custom chip color.
- added support for option function on EditingCompleted.
> added support for custom chip color and optional function on Editing Complete in form 

- CHANGELOG.md
- README.md
- pubspec.yaml
- Updated ChangeLog for version 3.0.4. 
- Formatted Code according to dart formatter.
- Updated Readme.md with Awesome Mobile Libraries.
> Updated ChangeLog for version 3.0.4

- example/lib/main.dart
- lib/credit_card_form.dart
> 🔨 Pub point issue fix

- .fvm/flutter_sdk
- .fvm/fvm_config.json
- .gitignore
.FVM folder added in gitignore
> :bug:FVM removed

- README.md
Updated Readme.md file 
Added Badge for Build and Version from Pub.dev
Added ChipColor Option
Added Optional function for onEditingComplete
Added All Global keys for everyTextfield
Added All Validator Functions for manual Validations
Updated Contributor's Data
> :construction: Updated Readme.md for new features

- README.md
Fixed Formatting issue in Readme.md file
> :bug: Fixed formatting issue in Readme.md

- CHANGELOG.md
Updated Changelog with Tag link for version 3.0.4
> :books: Updated CHANGELOG.md with Tag link

- pubspec.yaml
> :arrow_up: Upgraded SDK version

- pubspec.yaml
> :bug: Instant Release fixes

- CHANGELOG.md
New credit card brands commit/pr was added in CHANGELOG.md.
> CHANGELOG.md was updated

- README.md
- lib/constants.dart
- lib/credit_card_background.dart
- lib/credit_card_widget.dart
- lib/floating_animation/floating_config.dart
- lib/flutter_credit_card.dart
- Removed preset constructor for default config of floatConfig and floatShadowConfig.
- Switched from nullable fields for floatConfig and floatShadowConfig to the default constructor as default value.
- Added space between preview images in README.md.
> :ok_hand: Change FloatConfig initialization

- CHANGELOG.md
- analysis_options.yaml
- example/lib/main.dart
- example/pubspec.yaml
- lib/credit_card_animation.dart
- lib/credit_card_form.dart
- lib/credit_card_widget.dart
- pubspec.yaml
- Added dart 3 support.
- Added flutter_lints.
- Fixed warnings given by analyzer.
> :feat: Dart 3 Support

- CHANGELOG.md
- lib/src/credit_card_widget.dart
- Fixes [#157](https://github.com/SimformSolutionsPvtLtd/flutter_credit_card/issues/157)
> :bug: Safe guard adding new Floating events

- .github/pull_request_template.md
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- lib/src/credit_card_form.dart
- lib/src/utils/helpers.dart
- pubspec.yaml
Version Bump To 4.1.0  :rocket:
> chore: 🔖 version bump from 4.0.1 to 4.1.0 
